---
# This file tells https://pre-commit.com/
# which hooks are provided by this repo
# for use by other git repos.
- id: commitlint
  name: commitlint
  description: Commitlint hook
  language: docker_image
  entry: commitlint/commitlint:latest commitlint --edit
  pass_filenames: false
  always_run: true
- id: commitlint-travis
  name: Check commit messages on Travis CI
  description: Lint all relevant commits for a change or PR on Travis CI
  language: docker_image
  entry: commitlint/commitlint:latest commitlint-travis
  always_run: true
  pass_filenames: false